def world_attrs(overrides={})
  defaults = {
    tick_index: 0,
    tick_count: 20_000,
    width: 4000,
    height: 4000,
    players: [],
    wizards: [],
    minions: [],
    projectiles: [],
    bonuses: [],
    buildings: [],
    trees: []
  }

  attrs = defaults.merge overrides

  [
    attrs[:tick_index],
    attrs[:tick_count],
    attrs[:width],
    attrs[:height],
    attrs[:players],
    attrs[:wizards],
    attrs[:minions],
    attrs[:projectiles],
    attrs[:bonuses],
    attrs[:buildings],
    attrs[:trees],
  ]
end

def wizard_attrs(overrides={})
  defaults = {
    id: 1,
    x: 800,
    y: 800,
    speed_x: 0,
    speed_y: 0,
    angle: 0, # parallel O->X
    faction: Faction::ACADEMY,
    radius: 35,
    life: 100,
    max_life: 100,
    statuses: [],
    owner_player_id: 1,
    me: true,
    mana: 100,
    max_mana: 100,
    vision_range: 600,
    cast_range: 500,
    xp: 0,
    level: 0,
    skills: [],
    remaining_action_cooldown_ticks: 0,
    remaining_cooldown_ticks_by_action: [0, 0, 0, 0, 0, 0, 0],
    master: false, 
    messages: []
  }

  attrs = defaults.merge(overrides)

  [
    attrs[:id],
    attrs[:x],
    attrs[:y],
    attrs[:speed_x],
    attrs[:speed_y],
    attrs[:angle],
    attrs[:faction],
    attrs[:radius],
    attrs[:life],
    attrs[:max_life],
    attrs[:statuses],
    attrs[:owner_player_id],
    attrs[:me],
    attrs[:mana],
    attrs[:max_mana],
    attrs[:vision_range],
    attrs[:cast_range],
    attrs[:xp],
    attrs[:level],
    attrs[:skills],
    attrs[:remaining_action_cooldown_ticks],
    attrs[:remaining_cooldown_ticks_by_action],
    attrs[:master],
    attrs[:messages],
  ]
end

def tree_attrs(overrides={})
  defaults = {
    id: 300,
    x: 1200,
    y: 1200,
    speed_x: 0,
    speed_y: 0,
    angle: 0,
    faction: Faction::NEUTRAL,
    radius: 30,
    life: 15,
    max_life: 15,
    statuses: []
  }

  attrs = defaults.merge overrides

  [
    attrs[:id],
    attrs[:x],
    attrs[:y],
    attrs[:speed_x],
    attrs[:speed_y],
    attrs[:angle],
    attrs[:faction],
    attrs[:radius],
    attrs[:life],
    attrs[:max_life],
    attrs[:statuses],
  ]
end

def game_attrs(overrides={})
  defaults = {
    random_seed: 8276036883696445292,
    tick_count: 20000,
    map_size: 4000.0,
    skills_enabled: false,
    raw_messages_enabled: false,
    friendly_fire_damage_factor: 0.25,
    building_damage_score_factor: 0.25,
    building_elimination_score_factor: 0.25,
    minion_damage_score_factor: 0.0,
    minion_elimination_score_factor: 0.25,
    wizard_damage_score_factor: 0.25,
    wizard_elimination_score_factor: 1.0,
    team_working_score_factor: 1.67,
    victory_score: 1000,
    score_gain_range: 600.0,
    raw_message_max_length: 1024,
    raw_message_transmission_speed: 2.0,
    wizard_radius: 35.0,
    wizard_cast_range: 500.0,
    wizard_vision_range: 600.0,
    wizard_forward_speed: 4.0,
    wizard_backward_speed: 3.0,
    wizard_strafe_speed: 3.0,
    wizard_base_life: 100,
    wizard_life_growth_per_level: 10,
    wizard_base_mana: 100,
    wizard_mana_growth_per_level: 10,
    wizard_base_life_regeneration: 0.05,
    wizard_life_regeneration_growth_per_level: 0.005,
    wizard_base_mana_regeneration: 0.2,
    wizard_mana_regeneration_growth_per_level: 0.02,
    wizard_max_turn_angle: 0.10471975511965978,
    wizard_max_resurrection_delay_ticks: 2400,
    wizard_min_resurrection_delay_ticks: 1200,
    wizard_action_cooldown_ticks: 30,
    staff_cooldown_ticks: 60,
    magic_missile_cooldown_ticks: 60,
    frost_bolt_cooldown_ticks: 90,
    fireball_cooldown_ticks: 120,
    haste_cooldown_ticks: 120,
    shield_cooldown_ticks: 120,
    magic_missile_manacost: 12,
    frost_bolt_manacost: 36,
    fireball_manacost: 48,
    haste_manacost: 48,
    shield_manacost: 48,
    staff_damage: 12,
    staff_sector: 0.5235987755982988,
    staff_range: 70.0,
    level_up_xp_values: [],
    minion_radius: 25.0,
    minion_vision_range: 400.0,
    minion_speed: 3.0,
    minion_max_turn_angle: 0.10471975511965978,
    minion_life: 100,
    faction_minion_appearance_interval_ticks: 750,
    orc_woodcutter_action_cooldown_ticks: 60,
    orc_woodcutter_damage: 12,
    orc_woodcutter_attack_sector: 0.5235987755982988,
    orc_woodcutter_attack_range: 50.0,
    fetish_blowdart_action_cooldown_ticks: 30,
    fetish_blowdart_attack_range: 300.0,
    fetish_blowdart_attack_sector: 0.5235987755982988,
    bonus_radius: 20.0,
    bonus_appearance_interval_ticks: 2500,
    bonus_score_amount: 200,
    dart_radius: 5.0,
    dart_speed: 50.0,
    dart_direct_damage: 6,
    magic_missile_radius: 10.0,
    magic_missile_speed: 40.0,
    magic_missile_direct_damage: 12,
    frost_bolt_radius: 15.0,
    frost_bolt_speed: 35.0,
    frost_bolt_direct_damage: 24,
    fireball_radius: 20.0,
    fireball_speed: 30.0,
    fireball_explosion_max_damage_range: 20.0,
    fireball_explosion_min_damage_range: 100.0,
    fireball_explosion_max_damage: 24,
    fireball_explosion_min_damage: 12,
    guardian_tower_radius: 50.0,
    guardian_tower_vision_range: 600.0,
    guardian_tower_life: 500.0,
    guardian_tower_attack_range: 600.0,
    guardian_tower_damage: 36,
    guardian_tower_cooldown_ticks: 240,
    faction_base_radius: 100.0,
    faction_base_vision_range: 800.0,
    faction_base_life: 1000.0,
    faction_base_attack_range: 800.0,
    faction_base_damage: 48,
    faction_base_cooldown_ticks: 240,
    burning_duration_ticks: 240,
    burning_summary_damage: 24,
    empowered_duration_ticks: 2400,
    empowered_damage_factor: 2.0,
    frozen_duration_ticks: 60,
    hastened_duration_ticks: 600,
    hastened_bonus_duration_factor: 4.0,
    hastened_movement_bonus_factor: 0.3,
    hastened_rotation_bonus_factor: 0.5,
    shielded_duration_ticks: 600,
    shielded_bonus_duration_factor: 4.0,
    shielded_direct_damage_absorption_factor: 0.25,
    aura_skill_range: 500.0,
    range_bonus_per_skill_level: 25.0,
    magical_damage_bonus_per_skill_level: 1,
    staff_damage_bonus_per_skill_level: 3,
    movement_bonus_factor_per_skill_level: 0.05,
    magical_damage_absorption_per_skill_level: 1,
  }

  attrs = defaults.merge overrides

  [
    attrs[:random_seed],
    attrs[:tick_count],
    attrs[:map_size],
    attrs[:skills_enabled],
    attrs[:raw_messages_enabled],
    attrs[:friendly_fire_damage_factor],
    attrs[:building_damage_score_factor],
    attrs[:building_elimination_score_factor],
    attrs[:minion_damage_score_factor],
    attrs[:minion_elimination_score_factor],
    attrs[:wizard_damage_score_factor],
    attrs[:wizard_elimination_score_factor],
    attrs[:team_working_score_factor],
    attrs[:victory_score],
    attrs[:score_gain_range],
    attrs[:raw_message_max_length],
    attrs[:raw_message_transmission_speed],
    attrs[:wizard_radius],
    attrs[:wizard_cast_range],
    attrs[:wizard_vision_range],
    attrs[:wizard_forward_speed],
    attrs[:wizard_backward_speed],
    attrs[:wizard_strafe_speed],
    attrs[:wizard_base_life],
    attrs[:wizard_life_growth_per_level],
    attrs[:wizard_base_mana],
    attrs[:wizard_mana_growth_per_level],
    attrs[:wizard_base_life_regeneration],
    attrs[:wizard_life_regeneration_growth_per_level],
    attrs[:wizard_base_mana_regeneration],
    attrs[:wizard_mana_regeneration_growth_per_level],
    attrs[:wizard_max_turn_angle],
    attrs[:wizard_max_resurrection_delay_ticks],
    attrs[:wizard_min_resurrection_delay_ticks],
    attrs[:wizard_action_cooldown_ticks],
    attrs[:staff_cooldown_ticks],
    attrs[:magic_missile_cooldown_ticks],
    attrs[:frost_bolt_cooldown_ticks],
    attrs[:fireball_cooldown_ticks],
    attrs[:haste_cooldown_ticks],
    attrs[:shield_cooldown_ticks],
    attrs[:magic_missile_manacost],
    attrs[:frost_bolt_manacost],
    attrs[:fireball_manacost],
    attrs[:haste_manacost],
    attrs[:shield_manacost],
    attrs[:staff_damage],
    attrs[:staff_sector],
    attrs[:staff_range],
    attrs[:level_up_xp_values],
    attrs[:minion_radius],
    attrs[:minion_vision_range],
    attrs[:minion_speed],
    attrs[:minion_max_turn_angle],
    attrs[:minion_life],
    attrs[:faction_minion_appearance_interval_ticks],
    attrs[:orc_woodcutter_action_cooldown_ticks],
    attrs[:orc_woodcutter_damage],
    attrs[:orc_woodcutter_attack_sector],
    attrs[:orc_woodcutter_attack_range],
    attrs[:fetish_blowdart_action_cooldown_ticks],
    attrs[:fetish_blowdart_attack_range],
    attrs[:fetish_blowdart_attack_sector],
    attrs[:bonus_radius],
    attrs[:bonus_appearance_interval_ticks],
    attrs[:bonus_score_amount],
    attrs[:dart_radius],
    attrs[:dart_speed],
    attrs[:dart_direct_damage],
    attrs[:magic_missile_radius],
    attrs[:magic_missile_speed],
    attrs[:magic_missile_direct_damage],
    attrs[:frost_bolt_radius],
    attrs[:frost_bolt_speed],
    attrs[:frost_bolt_direct_damage],
    attrs[:fireball_radius],
    attrs[:fireball_speed],
    attrs[:fireball_explosion_max_damage_range],
    attrs[:fireball_explosion_min_damage_range],
    attrs[:fireball_explosion_max_damage],
    attrs[:fireball_explosion_min_damage],
    attrs[:guardian_tower_radius],
    attrs[:guardian_tower_vision_range],
    attrs[:guardian_tower_life],
    attrs[:guardian_tower_attack_range],
    attrs[:guardian_tower_damage],
    attrs[:guardian_tower_cooldown_ticks],
    attrs[:faction_base_radius],
    attrs[:faction_base_vision_range],
    attrs[:faction_base_life],
    attrs[:faction_base_attack_range],
    attrs[:faction_base_damage],
    attrs[:faction_base_cooldown_ticks],
    attrs[:burning_duration_ticks],
    attrs[:burning_summary_damage],
    attrs[:empowered_duration_ticks],
    attrs[:empowered_damage_factor],
    attrs[:frozen_duration_ticks],
    attrs[:hastened_duration_ticks],
    attrs[:hastened_bonus_duration_factor],
    attrs[:hastened_movement_bonus_factor],
    attrs[:hastened_rotation_bonus_factor],
    attrs[:shielded_duration_ticks],
    attrs[:shielded_bonus_duration_factor],
    attrs[:shielded_direct_damage_absorption_factor],
    attrs[:aura_skill_range],
    attrs[:range_bonus_per_skill_level],
    attrs[:magical_damage_bonus_per_skill_level],
    attrs[:staff_damage_bonus_per_skill_level],
    attrs[:movement_bonus_factor_per_skill_level],
    attrs[:magical_damage_absorption_per_skill_level]
  ]


end
